spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8081
  datasource:
    url: "jdbc:postgresql://localhost:5432/springbootjpa"
    username: jpatutorial
    password: Test

